# Tell Netlify where the package.json is
base = "frontend"

[build]
  command = "npm run build"
  publish = "frontend/out"

[dev]
  command = "npm run dev"
  framework = "next"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
